#!/bin/sh

for insert in L A B R S V
do
	for order in A
	do
	    for size in 1000 2000 3000 4000 5000
	    do
		    echo ""
		    echo "Test: ./tlab $size $order $insert"
		    echo "t" | ./tlab $size $order $insert | grep -v Tree
	    done
	done
done
